// TO FIND THE AREA OF A TRIANGLE
// WHERE THE BASE OF THE TRIANGLE IS YOUR BIRTH MONTH (APRIL = 04)
// AND PERPENDICULAR HEIGHT IS YOUR BIRTH DATE (11)
// FORMULA FOR AREA = 1/2 * BASE * HEIGHT

ORG 0000H
	MOV A, 30H
	MOV B, 31H
	MUL AB
	MOV 41H, A
	MOV 40H, B
	MOV B, #2H
	DIV AB
	MOV 42H, A
	MOV 43H, B
	END